version: '3.0'
 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
  demoapi:
    image: appdesign/demoapi
    build:
      context: .
    depends_on:
        - db
    ports:
       - "8080:80"
volumes:
  dbdata:       